version: "3.9"

services: 
  api:
    container_name: api
    image: api_express
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=jorge
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB=products_management
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=jorge
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jorge -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
